export type Unit = "m" | "ft" | "cm";

export interface Point {
  x: number;
  y: number;
}

export type WallMode = "fill" | "outline" | "line" | "mitered" | "mitered-union";
/** Spine placement relative to wall thickness: centerline, or flush on one side along the segment. */
export type WallMethod = "left" | "center" | "right";

/** Segment type: wall, door opening, window opening, plot boundary, layout connection edge, or
 *  the buildable / footprint boundary lines that wrap their corresponding Space types. */
export type WallSegmentType = "wall" | "door" | "window" | "plot-boundary" | "connection"
  | "buildable-boundary" | "footprint-boundary" | "path";

/** Corner style for `segmentType: "path"` segments at junctions where consecutive
 *  path segments meet. "miter" = angular (existing wall-style join); "round" = the
 *  outer corner is replaced with an arc of radius `thickness/2`; "nurbs" = the
 *  entire chain of connected path segments is replaced with a smooth cubic NURBS
 *  curve through the vertices and rendered as an offset ribbon of width `thickness`.
 *  Defaults to "miter" when omitted. Has no effect on non-path segments. */
export type PathJoin = "miter" | "round" | "nurbs";

/** Connection-segment metadata: when segmentType === "connection", these reference the two rooms the edge links. */
export interface ConnectionWallMeta {
  aRoomId?: string;
  bRoomId?: string;
}

export interface Wall {
  id: string;
  start: Point;
  end: Point;
  /** Layer this wall lives on. Missing/unknown values resolve to `DEFAULT_LAYER_ID` (`"0"`). */
  layerId?: string;
  /** Optional spine polyline for curved walls (x1, y1, x2, y2, ...). */
  spinePoints?: number[];
  /** Konva Line tension used when rendering spinePoints as a spline. */
  splineTension?: number;
  thickness: number;
  color: string;
  dashed?: boolean;
  /** fill = solid wall; outline = hollow rectangle stroke only */
  mode?: WallMode;
  /** How the start→end spine aligns to the wall thickness */
  method?: WallMethod;
  /** Segment type: built-in (`wall` / `door` / `window` / `plot-boundary` / `path`) or a
   *  custom slug registered in `FloorPlanModel.customSegmentTypes`. */
  segmentType?: WallSegmentType | string;
  /** Corner join style when `segmentType === "path"`. Defaults to "miter" if omitted.
   *  Ignored for all other segment types. */
  pathJoin?: PathJoin;
  /** When `pathJoin === "nurbs"`, controls whether the curve passes exactly through
   *  each vertex (interpolating Catmull-Rom) or approximates the polyline (B-spline). */
  nurbsInterpolate?: boolean;
  /** Per-wall values for parameters declared by a custom segment type's schema.
   *  Keyed by ParamDef.key. Built-in segment types ignore this field. */
  customParams?: Record<string, string | number | boolean>;
  /** Optional user-editable label shown in the properties panel. */
  label?: string;
  /** Optional user-selected category for the segment. */
  category?: "Fire Exit" | "Facade" | "Electrical Entrance" | "Lift Entrance";
  /** When true, render an arrowhead at the segment's midpoint pointing from start → end. */
  showDirection?: boolean;
  /** When true, render the segment's convergence/divergence level number on it. */
  showLevel?: boolean;
  /** Whether this wall was generated by compute floorplate. */
  isFloorplateComputed?: boolean;
  /** ID of the floorplate-boundary room this wall belongs to (set on BSP-generated layout walls). */
  floorplateId?: string;
  /** Whether this wall was generated by GCR buildable area computation. */
  isGcrComputed?: boolean;
  /** Whether this wall was generated by max inscribed rectangle computation. */
  isMaxRectComputed?: boolean;
  /** Live-preview variant of max inscribed rectangle — excluded from room detection. */
  isMaxRectPreview?: boolean;
  /** Whether this wall was generated by Optimise L-shape computation (committed). */
  isOptLShapeWall?: boolean;
  /** Live-preview variant of Optimise L-shape — excluded from room detection. */
  isOptLShapePreview?: boolean;
  /** Source room id for Optimise L-shape walls (preview & committed). */
  optLShapeSourceRoomId?: string;
  /** Wall belongs to a placed rectangle along the boundary (permanent). */
  isPlacementWall?: boolean;
  /** Live-preview variant of boundary placement — excluded from room detection. */
  isPlacementPreview?: boolean;
  /** Source room id for placement walls. */
  placementSourceRoomId?: string;
  /** Stable id of the PlacedObject this placement-wall belongs to (groups the 4 sides). */
  placementObjectId?: string;
  /** Kind of placed object — drives 2D-symbol rendering in 2D Symbol placement mode. */
  placementKind?:
    | "bed" | "table" | "chair" | "sofa"
    | "desk" | "wardrobe" | "bookshelf" | "bench"
    | "piano" | "tv-unit" | "fridge" | "toilet" | "bathtub"
    | "guitar" | "whiteboard" | "flute" | "clock" | "mirror";
  /** Height in metres of the placed object (used by 3D primitive in 2D Symbol mode). */
  placementHeightM?: number;
  /** Clearance from floor in metres (lift wall-hung objects above floor). */
  placementClearanceM?: number;
  /** Wall belongs to a committed Voronoi partition. */
  isVoronoiWall?: boolean;
  /** Live-preview variant of Voronoi partition — excluded from room detection. */
  isVoronoiPreview?: boolean;
  /** Source room id for voronoi walls. */
  voronoiSourceRoomId?: string;
  /** Wall belongs to a committed polygon skeleton (medial axis). */
  isSkeletonWall?: boolean;
  /** Live-preview variant of polygon skeleton — excluded from room detection. */
  isSkeletonPreview?: boolean;
  /** Source room id for skeleton walls. */
  skeletonSourceRoomId?: string;
  /** Wall belongs to a committed convex hull. */
  isConvexHullWall?: boolean;
  /** Live-preview variant of convex hull — excluded from room detection. */
  isConvexHullPreview?: boolean;
  /** Source room id for convex hull walls. */
  convexHullSourceRoomId?: string;
  /** Wall belongs to a committed inflation (soap-film) inscribed rectangle. */
  isInflationWall?: boolean;
  /** Live-preview variant of inflation rectangle — excluded from room detection. */
  isInflationPreview?: boolean;
  /** Source room id for inflation rectangle walls. */
  inflationSourceRoomId?: string;
  /** Wall belongs to a committed BSP partition. */
  isBspWall?: boolean;
  /** Live-preview variant of BSP partition — excluded from room detection. */
  isBspPreview?: boolean;
  /** Source room id for BSP walls. */
  bspSourceRoomId?: string;
  /** Wall belongs to a committed RFP (Rectangular Floor Plan) partition. */
  isRfpWall?: boolean;
  /** Live-preview variant of RFP partition — excluded from room detection. */
  isRfpPreview?: boolean;
  /** Source room id for RFP walls. */
  rfpSourceRoomId?: string;
  /** Wall belongs to a committed rectangular decomposition. */
  isRectDecompWall?: boolean;
  /** Live-preview variant of rectangular decomposition — excluded from room detection. */
  isRectDecompPreview?: boolean;
  /** Source room id for rectangular decomposition walls. */
  rectDecompSourceRoomId?: string;
  /** Wall belongs to a committed Delaunay triangulation. */
  isDelaunayWall?: boolean;
  /** Live-preview variant of Delaunay triangulation — excluded from room detection. */
  isDelaunayPreview?: boolean;
  /** Source room id for Delaunay walls. */
  delaunaySourceRoomId?: string;
  /** Wall belongs to a committed polygon-smoothing curve. */
  isSmoothingWall?: boolean;
  /** Live-preview variant of polygon smoothing — excluded from room detection. */
  isSmoothingPreview?: boolean;
  /** Source room id for smoothing walls. */
  smoothingSourceRoomId?: string;
  /** Wall belongs to a committed polygon mesh triangulation. */
  isMeshWall?: boolean;
  /** Live-preview variant of polygon meshing — excluded from room detection. */
  isMeshPreview?: boolean;
  /** Source room id for mesh walls. */
  meshSourceRoomId?: string;
  /** Wall belongs to a committed CVT (centroidal Voronoi tessellation) cell boundary. */
  isCvtWall?: boolean;
  /** Live-preview variant of CVT relaxation — excluded from room detection. */
  isCvtPreview?: boolean;
  /** Source room id for CVT walls. */
  cvtSourceRoomId?: string;
  /** Wall belongs to a committed convex decomposition. */
  isConvexDecompWall?: boolean;
  /** Live-preview variant of convex decomposition — excluded from room detection. */
  isConvexDecompPreview?: boolean;
  /** Source room id for convex-decomposition walls. */
  convexDecompSourceRoomId?: string;
  /** Wall belongs to a committed circumcircle (minimum enclosing circle) of a room. */
  isCircumcircleWall?: boolean;
  /** Live-preview variant of circumcircle — excluded from room detection. */
  isCircumcirclePreview?: boolean;
  /** Source room id for circumcircle walls. */
  circumcircleSourceRoomId?: string;
  /** Wall belongs to a committed minimum enclosing ellipse of a room. */
  isEllipseWall?: boolean;
  /** Live-preview variant of minimum enclosing ellipse — excluded from room detection. */
  isEllipsePreview?: boolean;
  /** Source room id for ellipse walls. */
  ellipseSourceRoomId?: string;
  /** Wall belongs to a committed oriented bounding box of a room. */
  isObbWall?: boolean;
  /** Live-preview variant of oriented bounding box — excluded from room detection. */
  isObbPreview?: boolean;
  /** Source room id for OBB walls. */
  obbSourceRoomId?: string;
  /** Wall belongs to a committed regular n-gon enclosure of a room. */
  isNGonWall?: boolean;
  /** Live-preview variant of n-gon enclosure — excluded from room detection. */
  isNGonPreview?: boolean;
  /** Source room id for n-gon walls. */
  nGonSourceRoomId?: string;
  /** Wall belongs to a committed polygon-unroll visualization of a room. */
  isUnrollWall?: boolean;
  /** Live-preview variant of polygon unroll — excluded from room detection. */
  isUnrollPreview?: boolean;
  /** Source room id for unroll walls. */
  unrollSourceRoomId?: string;
  /** Wall belongs to a committed principal-axes overlay of a room. */
  isPrincipalAxisWall?: boolean;
  /** Live-preview variant of principal-axes overlay — excluded from room detection. */
  isPrincipalAxisPreview?: boolean;
  /** Source room id for principal-axis walls. */
  principalAxisSourceRoomId?: string;
  /** Wall belongs to a committed contour-line overlay of a room. */
  isContourWall?: boolean;
  /** Live-preview variant of contour-line overlay — excluded from room detection. */
  isContourPreview?: boolean;
  /** Source room id for contour walls. */
  contourSourceRoomId?: string;
  /** Wall belongs to a committed streamlines overlay of a room. */
  isStreamlineWall?: boolean;
  /** Live-preview variant of streamlines overlay — excluded from room detection. */
  isStreamlinePreview?: boolean;
  /** Source room id for streamline walls. */
  streamlineSourceRoomId?: string;
  /** Wall belongs to a committed noise-texture overlay of a room. */
  isNoiseTextureWall?: boolean;
  /** Live-preview variant of noise-texture overlay — excluded from room detection. */
  isNoiseTexturePreview?: boolean;
  /** Source room id for noise-texture walls. */
  noiseTextureSourceRoomId?: string;
  /** Wall belongs to a committed incircle overlay of a room. */
  isInCircleWall?: boolean;
  /** Live-preview variant of incircle overlay — excluded from room detection. */
  isInCirclePreview?: boolean;
  /** Source room id for incircle walls. */
  inCircleSourceRoomId?: string;
  /** Wall belongs to a committed tiling overlay of a room. */
  isTilingWall?: boolean;
  /** Live-preview variant of tiling overlay — excluded from room detection. */
  isTilingPreview?: boolean;
  /** Source room id for tiling walls. */
  tilingSourceRoomId?: string;
  /** Wall belongs to a committed squarified-treemap partition. */
  isTreemapWall?: boolean;
  /** Live-preview variant of squarified-treemap partition — excluded from room detection. */
  isTreemapPreview?: boolean;
  /** Source room id for treemap walls. */
  treemapSourceRoomId?: string;
  /** Whether this wall was generated by the Splitting Actions panel for a room. */
  isSplitWall?: boolean;
  /** Source room id for walls generated by Splitting Actions. */
  splitSourceRoomId?: string;
  /** Whether this wall was generated by the Inset Polygon panel for a room (live preview). */
  isInsetWall?: boolean;
  /** Source room id for walls generated by Inset Polygon. */
  insetSourceRoomId?: string;
  /** Wall belongs to a committed Massing facade (boundary windows + door). */
  isMassingWall?: boolean;
  /** Live-preview variant of Massing facade — excluded from room detection. */
  isMassingPreview?: boolean;
  /** Source room id for walls generated by Massing. */
  massingSourceRoomId?: string;
  /** Wall is the perimeter of a Path Setter–generated Space (committed). */
  isPathSpaceWall?: boolean;
  /** Live-preview variant of Path Setter perimeter — excluded from room detection. */
  isPathSpacePreview?: boolean;
  /** Source room id for walls / rooms generated by Path Setter. */
  pathSpaceSourceRoomId?: string;
  /** Per-segment height in metres (applies to "wall" and "plot-boundary" segments). */
  heightM?: number;
  /** Site Boundary only: physical treatment of the boundary line. */
  boundaryTreatment?: "fence" | "railing" | "open" | "solid" | "gate";
  /** Site Boundary only: regulatory adjacency that drives setback / NOC requirements (Indian context). */
  setbackRegime?: "road" | "adjoining-plot" | "nala-drain" | "water-body" | "restricted-zone" | "green-open-space";
  /** Site Boundary + setbackRegime="road" only: abutting road width in metres (drives tiered setback). */
  roadWidthM?: number;
  /** Wall produced by Add Openings (committed). */
  isOpeningWall?: boolean;
  /** Live-preview variant of Add Openings — excluded from room detection. */
  isOpeningPreview?: boolean;
  /** Source wall id for walls generated by Add Openings. */
  openingSourceWallId?: string;
  /** Door only: which end the hinge is on. "left" = start end, "right" = end end. */
  doorHinge?: "left" | "right";
  /** Door only: which side the door swings into. "left" = perpendicular left, "right" = perpendicular right. */
  doorPlacement?: "left" | "right";
  /** Door / Window: height from floor to top of opening, in meters. */
  lintelHeightM?: number;
  /** Window only: height from floor to bottom of opening, in meters. */
  sillHeightM?: number;
  /** Window only: when true, the 3D primitive renders the sash swung open; 2D is unaffected. */
  isOpen?: boolean;
  /** Plot boundary only: sub-type. */
  plotBoundaryType?: "road" | "plot" | "open" | "reservation" | "water" | "row";
  /** Plot boundary only: computed setback in meters. */
  setbackM?: number;
  /** Plot boundary + Road: road width in meters. */
  roadWidthM?: number;
  /** Plot boundary + Plot: whether it's a blank wall (no openings). */
  blankWall?: boolean;
  /** Plot boundary + Water: water body subtype. */
  waterSubtype?: "river" | "nala" | "lake" | "sea" | "canal";
  /** Plot boundary + Water: CRZ zone. */
  crzZone?: "I" | "II" | "III" | "IV";
  /** Plot boundary + ROW: ROW subtype. */
  rowSubtype?: "railway" | "metro" | "ht_line" | "pipeline" | "highway";

  // ── DCR / Regulation properties (plot boundary) ──
  /** Ground coverage percentage (e.g. 40) */
  groundCoveragePct?: number;
  /** Maximum building height in meters */
  maxHeightM?: number;
  /** Floor-to-floor height in meters */
  floorToFloorM?: number;
  /** Applicable regulation code (e.g. "DCR 33(7B)") */
  regulation?: string;
  /** Zone classification */
  zone?: string;

  // ── FSI properties (plot boundary) ──
  /** FSI multiplier for this segment */
  fsiMultiplier?: number;
  /** Deduction area in sq.m. (DP road / reservation segments) */
  deductionAreaSqm?: number;
  /** Whether this is surrendered land */
  isSurrenderedLand?: boolean;
  /** In-situ FSI available */
  inSituFsiAvailable?: number;

  // ── Entry / Access properties (plot boundary) ──
  /** Whether main entry is allowed from this side */
  allowsMainEntry?: boolean;
  /** Whether windows are allowed on this side */
  allowsWindows?: boolean;
  /** Whether NOC is required */
  nocRequired?: boolean;
  /** Whether this is the primary frontage */
  isPrimaryFrontage?: boolean;
  /** Proposed road widening in meters */
  proposedWideningM?: number;

  /** Connection-type segment: rooms whose centroids the segment links. */
  aRoomId?: string;
  bRoomId?: string;
}

/** Derived rectangle: four edges + spine. Computed from Wall via getWallPolygonGeometry in wallGeometry.ts. */
export interface WallPolygonGeometry {
  corners: Point[];
  edges: [Point, Point][];
  /** Center line along the wall (same as start → end). */
  spine: { start: Point; end: Point };
}

/** Room/area type classification.
 *  Built-in slugs are kept as a string union for code paths that branch on them.
 *  User-defined types extend this set at runtime via `FloorPlanModel.customRoomTypes`,
 *  so consumers should treat `roomType` as `string` when dealing with arbitrary values. */
export type RoomType = "room" | "floorplate-boundary" | "plot-boundary" | "buildable-area" | "path";

/** Schema for a single user-defined parameter on a custom room type. */
export type ParamDef =
  | { key: string; label: string; kind: "number"; min?: number; max?: number; step?: number; default?: number; unit?: string }
  | { key: string; label: string; kind: "text"; default?: string }
  | { key: string; label: string; kind: "boolean"; default?: boolean }
  | { key: string; label: string; kind: "select"; options: string[]; default?: string };

/** User-defined area type definition. Stored under FloorPlanModel.customRoomTypes
 *  keyed by the type's slug; the slug is what gets written to room.roomType. */
export interface AreaTypeDef {
  /** Unique slug (lowercased identifier) — matches the value stored in room.roomType. */
  id: string;
  /** Display name shown in the type dropdown and properties header. */
  displayName: string;
  /** Optional fill colour for rooms of this type (CSS colour). */
  fill?: string;
  /** Schema describing the parameters this type exposes in the INPUTS panel. */
  params: ParamDef[];
}

export interface Room {
  id: string;
  points: Point[];
  /** Layer this room lives on. Missing/unknown values resolve to `DEFAULT_LAYER_ID` (`"0"`). */
  layerId?: string;
  /** Inner rings carved out of this room (holes). Mostly meaningful on
   *  plot-boundary rooms that contain a footprint/building. Derived on the fly
   *  by `getRoomHoles(room, rooms)` so callers usually don't need to set this
   *  explicitly — it's exposed for serialization and future manual overrides. */
  holes?: Point[][];
  fill: string;
  stroke: string;
  label?: string;
  netArea?: number;
  /** Area type: built-in (`room` / `floorplate-boundary` / `plot-boundary`) or a custom slug
   *  registered in `FloorPlanModel.customRoomTypes`. Code paths that branch on the built-ins
   *  use string equality, so widening to `string` here doesn't break narrowing in practice. */
  roomType?: RoomType | string;
  /** Region classification for rooms (only meaningful when roomType === "room"). */
  region?: "Core" | "Staircase" | "AHU" | "Electrical Room" | "Service" | "Lift" | "Toilet" | "Corridor";
  /** Zone-type sizing constraints used by the ZR pipeline. All optional, in metres² / dimensionless. */
  minArea?: number;
  maxArea?: number;
  maxRatio?: number;
  /** When true, render a clockwise/anticlockwise direction icon at the room's centroid. */
  showDirection?: boolean;
  // ── Site plan properties (plot-boundary rooms only) ──
  /** Ground coverage percentage */
  groundCoveragePct?: number;
  /** Maximum building height in meters */
  maxHeightM?: number;
  /** Floor-to-floor height in meters */
  floorToFloorM?: number;
  /** Maximum permissible FSI */
  maxFsi?: number;
  /** Applicable regulation code */
  regulation?: string;
  /** Max polygon optimization type */
  maxPolygonType?: "normal" | "axis-aligned" | "edge-sitting";
  /** Zone classification */
  zone?: string;
  /** Massing: number of floors to render in 3D (default 1). */
  floorsCount?: number;
  /** Room produced by Path Setter live preview — excluded from room detection / commit. */
  isPathSpacePreview?: boolean;
  /** Source host-room id for Path Setter–generated spaces. */
  pathSpaceSourceRoomId?: string;
  /** Per-room values for parameters declared by a custom room type's schema.
   *  Keyed by ParamDef.key. Built-in types ignore this field. */
  customParams?: Record<string, string | number | boolean>;
}

export type ObjectKind = "rect" | "circle" | "polygon" | "freehand" | "text" | "segment";

export type Tool =
  | "select"
  | "wall"
  | "room"
  | "rect"
  | "circle"
  | "freehand"
  | "text"
  | "segment"
  | "measure"
  | "scale"
  | "pan"
  | "door"
  | "window"
  | "point";

export interface BaseObject {
  id: string;
  /** Layer this object lives on. Missing/unknown values resolve to `DEFAULT_LAYER_ID` (`"0"`). */
  layerId?: string;
  x: number;
  y: number;
  rotation: number;
  stroke: string;
  fill: string;
}

export interface RectObject extends BaseObject {
  kind: "rect";
  width: number;
  height: number;
}

export interface CircleObject extends BaseObject {
  kind: "circle";
  radius: number;
}

export interface PolygonObject extends BaseObject {
  kind: "polygon";
  points: number[];
}

export interface FreehandObject extends BaseObject {
  kind: "freehand";
  points: number[];
}

export interface TextObject extends BaseObject {
  kind: "text";
  text: string;
  fontSize: number;
}

export type SegmentSubtype = "drawn" | "adjacency";
export type AdjacencyConstraint = "connection" | "repulsion";

export interface SegmentObject extends BaseObject {
  kind: "segment";
  points: number[];
  measurements: string[];
  totalText: string;
  /** "drawn" (default, manually drawn) or "adjacency" (auto-computed between two rooms). */
  segmentSubtype?: SegmentSubtype;
  /** For adjacency subtype: endpoints reference room IDs and points are derived from centroids. */
  aRoomId?: string;
  bRoomId?: string;
  /** For adjacency subtype: the relation type. */
  constraint?: AdjacencyConstraint;
}

export type FloorObject = RectObject | CircleObject | PolygonObject | FreehandObject | TextObject | SegmentObject;

export interface FurnitureItem {
  id: string;
  type: "bed" | "sofa" | "table" | "chair" | "door" | "window";
  /** Layer this furniture lives on. Missing/unknown values resolve to `DEFAULT_LAYER_ID` (`"0"`). */
  layerId?: string;
  x: number;
  y: number;
  rotation: number;
  scaleX: number;
  scaleY: number;
  /** Door only: swing arc sweep in degrees (0 = closed, 90 = fully open). Default 90 when omitted. */
  doorSwingDeg?: number;
  /** Door only: when true, swing arc opens on the opposite face of the wall (inside vs outside in plan). */
  doorSwingFlip?: boolean;
  /** Door only: the two room labels this door connects. Used to reposition when rooms move. */
  connectionRooms?: [string, string];
}

export interface ImageUnderlay {
  src: string;
  x: number;
  y: number;
  width: number;
  height: number;
  opacity: number;
  scale: number;
  locked: boolean;
}

export interface RoomConstraint {
  label: string;
  minArea: number;
  maxRatio: number;
}

export interface FloorPlanModel {
  walls: Wall[];
  rooms: Room[];
  objects: FloorObject[];
  furniture: FurnitureItem[];
  imageUnderlay: ImageUnderlay | null;
  constraints?: {
    rooms: RoomConstraint[];
    connections: [string, string][];
  };
  /** User-defined room-type registry. Keyed by slug (= the value stored in room.roomType).
   *  Built-in types (`room`, `floorplate-boundary`, `plot-boundary`) are NOT stored here —
   *  they remain hardcoded so existing code paths keep working unchanged. */
  customRoomTypes?: Record<string, AreaTypeDef>;
  /** User-defined segment-type registry. Keyed by slug (= the value stored in wall.segmentType).
   *  Built-ins (`wall`, `door`, `window`, `plot-boundary`) are NOT stored here. */
  customSegmentTypes?: Record<string, AreaTypeDef>;
  /** AutoCAD-style layer table. Always non-empty (a default `"0"` layer is seeded).
   *  Per-entity `layerId` references entries here; missing/unknown references resolve to `"0"`. */
  layers?: Layer[];
}

/** AutoCAD-style layer. Every drawable entity carries a `layerId` referencing one of these. */
export interface Layer {
  id: string;
  name: string;
  color: string;
  visible: boolean;
  locked: boolean;
  /** Paint order — higher values draw on top. Default `0` for the seed layer. */
  order: number;
}

/** Built-in default layer id. Always present in `FloorPlanModel.layers` and cannot be deleted. */
export const DEFAULT_LAYER_ID = "0";

/** Returns a fresh seed layer table containing the default `"0"` layer plus
 *  Wall / Door / Window. Created entities are auto-stamped onto the appropriate
 *  layer by segmentType so users get sensible defaults without having to set
 *  the active layer first. */
export const DEFAULT_WALL_LAYER_ID = "wall";
export const DEFAULT_DOOR_LAYER_ID = "door";
export const DEFAULT_WINDOW_LAYER_ID = "window";
export const DEFAULT_FURNITURE_LAYER_ID = "furniture";
export const defaultLayerTable = (): Layer[] => [
  { id: DEFAULT_LAYER_ID,             name: "0",         color: "#000000", visible: true, locked: false, order: 0 },
  { id: DEFAULT_WALL_LAYER_ID,        name: "Wall",      color: "#475569", visible: true, locked: false, order: 1 },
  { id: DEFAULT_DOOR_LAYER_ID,        name: "Door",      color: "#b45309", visible: true, locked: false, order: 2 },
  { id: DEFAULT_WINDOW_LAYER_ID,      name: "Window",    color: "#0ea5e9", visible: true, locked: false, order: 3 },
  { id: DEFAULT_FURNITURE_LAYER_ID,   name: "Furniture", color: "#22c55e", visible: true, locked: false, order: 4 },
];

/** Migrate a (possibly older) FloorPlanModel into the layer-aware shape:
 *  – ensure `model.layers` exists and contains the default `"0"` layer
 *  – stamp `layerId = "0"` on every drawable entity that's missing it
 *  Call this on any model loaded from external storage (JSON file, project API). */
export const withLayerDefaults = (model: FloorPlanModel): FloorPlanModel => {
  const existing = model.layers && model.layers.length > 0 ? model.layers : [];
  const haveIds = new Set(existing.map((l) => l.id));
  // Add any built-in default layers (0, Wall, Door, Window) that the loaded model
  // is missing, without disturbing the user's other custom layers or their order.
  const seeds = defaultLayerTable().filter((s) => !haveIds.has(s.id));
  const layers: Layer[] = [...seeds, ...existing];
  const stamp = <T extends { layerId?: string }>(arr: T[] | undefined): T[] =>
    (arr ?? []).map((e) => (e.layerId ? e : { ...e, layerId: DEFAULT_LAYER_ID }));
  return {
    ...model,
    layers,
    walls: stamp(model.walls),
    rooms: stamp(model.rooms),
    objects: stamp(model.objects),
    furniture: stamp(model.furniture),
  };
};

/** Stored state from an auto-generated floor plan, enabling interactive room dragging. */
export interface GeneratedLayoutState {
  /** The generation config used (boundary, rooms, connections, etc.) */
  config: import("./floorplanAlgorithms").GenerateConfig;
  /** Current seed positions in meters (used to re-run BSP on drag) */
  seedPositions: Record<string, { x: number; y: number }>;
  /** Current room rectangles in pixel coords (for hit-testing drag targets) */
  roomRects: Array<{ label: string; x: number; y: number; w: number; h: number }>;
}
