export type Unit = "m" | "ft" | "cm";

export interface Point {
  x: number;
  y: number;
}

export type WallMode = "fill" | "outline" | "line" | "mitered" | "mitered-union";
/** Spine placement relative to wall thickness: centerline, or flush on one side along the segment. */
export type WallMethod = "left" | "center" | "right";

/** Segment type: wall, door opening, window opening, or plot boundary. */
export type WallSegmentType = "wall" | "door" | "window" | "plot-boundary";

export interface Wall {
  id: string;
  start: Point;
  end: Point;
  /** Optional spine polyline for curved walls (x1, y1, x2, y2, ...). */
  spinePoints?: number[];
  /** Konva Line tension used when rendering spinePoints as a spline. */
  splineTension?: number;
  thickness: number;
  color: string;
  dashed?: boolean;
  /** fill = solid wall; outline = hollow rectangle stroke only */
  mode?: WallMode;
  /** How the start→end spine aligns to the wall thickness */
  method?: WallMethod;
  /** Segment type: wall (default), door opening, or window opening. */
  segmentType?: WallSegmentType;
  /** Optional user-editable label shown in the properties panel. */
  label?: string;
  /** Optional user-selected category for the segment. */
  category?: "Fire Exit" | "Facade" | "Electrical Entrance" | "Lift Entrance";
  /** When true, render an arrowhead at the segment's midpoint pointing from start → end. */
  showDirection?: boolean;
  /** When true, render the segment's convergence/divergence level number on it. */
  showLevel?: boolean;
  /** Whether this wall was generated by compute floorplate. */
  isFloorplateComputed?: boolean;
  /** ID of the floorplate-boundary room this wall belongs to (set on BSP-generated layout walls). */
  floorplateId?: string;
  /** Whether this wall was generated by GCR buildable area computation. */
  isGcrComputed?: boolean;
  /** Whether this wall was generated by max inscribed rectangle computation. */
  isMaxRectComputed?: boolean;
  /** Live-preview variant of max inscribed rectangle — excluded from room detection. */
  isMaxRectPreview?: boolean;
  /** Wall belongs to a placed rectangle along the boundary (permanent). */
  isPlacementWall?: boolean;
  /** Live-preview variant of boundary placement — excluded from room detection. */
  isPlacementPreview?: boolean;
  /** Source room id for placement walls. */
  placementSourceRoomId?: string;
  /** Stable id of the PlacedObject this placement-wall belongs to (groups the 4 sides). */
  placementObjectId?: string;
  /** Kind of placed object — drives 2D-symbol rendering in 2D Symbol placement mode. */
  placementKind?:
    | "bed" | "table" | "chair" | "sofa"
    | "desk" | "wardrobe" | "bookshelf" | "bench"
    | "piano" | "tv-unit" | "fridge" | "toilet" | "bathtub"
    | "guitar" | "whiteboard" | "flute" | "clock" | "mirror";
  /** Height in metres of the placed object (used by 3D primitive in 2D Symbol mode). */
  placementHeightM?: number;
  /** Clearance from floor in metres (lift wall-hung objects above floor). */
  placementClearanceM?: number;
  /** Wall belongs to a committed Voronoi partition. */
  isVoronoiWall?: boolean;
  /** Live-preview variant of Voronoi partition — excluded from room detection. */
  isVoronoiPreview?: boolean;
  /** Source room id for voronoi walls. */
  voronoiSourceRoomId?: string;
  /** Wall belongs to a committed polygon skeleton (medial axis). */
  isSkeletonWall?: boolean;
  /** Live-preview variant of polygon skeleton — excluded from room detection. */
  isSkeletonPreview?: boolean;
  /** Source room id for skeleton walls. */
  skeletonSourceRoomId?: string;
  /** Wall belongs to a committed convex hull. */
  isConvexHullWall?: boolean;
  /** Live-preview variant of convex hull — excluded from room detection. */
  isConvexHullPreview?: boolean;
  /** Source room id for convex hull walls. */
  convexHullSourceRoomId?: string;
  /** Wall belongs to a committed BSP partition. */
  isBspWall?: boolean;
  /** Live-preview variant of BSP partition — excluded from room detection. */
  isBspPreview?: boolean;
  /** Source room id for BSP walls. */
  bspSourceRoomId?: string;
  /** Wall belongs to a committed rectangular decomposition. */
  isRectDecompWall?: boolean;
  /** Live-preview variant of rectangular decomposition — excluded from room detection. */
  isRectDecompPreview?: boolean;
  /** Source room id for rectangular decomposition walls. */
  rectDecompSourceRoomId?: string;
  /** Wall belongs to a committed Delaunay triangulation. */
  isDelaunayWall?: boolean;
  /** Live-preview variant of Delaunay triangulation — excluded from room detection. */
  isDelaunayPreview?: boolean;
  /** Source room id for Delaunay walls. */
  delaunaySourceRoomId?: string;
  /** Wall belongs to a committed polygon-smoothing curve. */
  isSmoothingWall?: boolean;
  /** Live-preview variant of polygon smoothing — excluded from room detection. */
  isSmoothingPreview?: boolean;
  /** Source room id for smoothing walls. */
  smoothingSourceRoomId?: string;
  /** Wall belongs to a committed polygon mesh triangulation. */
  isMeshWall?: boolean;
  /** Live-preview variant of polygon meshing — excluded from room detection. */
  isMeshPreview?: boolean;
  /** Source room id for mesh walls. */
  meshSourceRoomId?: string;
  /** Wall belongs to a committed CVT (centroidal Voronoi tessellation) cell boundary. */
  isCvtWall?: boolean;
  /** Live-preview variant of CVT relaxation — excluded from room detection. */
  isCvtPreview?: boolean;
  /** Source room id for CVT walls. */
  cvtSourceRoomId?: string;
  /** Wall belongs to a committed convex decomposition. */
  isConvexDecompWall?: boolean;
  /** Live-preview variant of convex decomposition — excluded from room detection. */
  isConvexDecompPreview?: boolean;
  /** Source room id for convex-decomposition walls. */
  convexDecompSourceRoomId?: string;
  /** Wall belongs to a committed circumcircle (minimum enclosing circle) of a room. */
  isCircumcircleWall?: boolean;
  /** Live-preview variant of circumcircle — excluded from room detection. */
  isCircumcirclePreview?: boolean;
  /** Source room id for circumcircle walls. */
  circumcircleSourceRoomId?: string;
  /** Wall belongs to a committed minimum enclosing ellipse of a room. */
  isEllipseWall?: boolean;
  /** Live-preview variant of minimum enclosing ellipse — excluded from room detection. */
  isEllipsePreview?: boolean;
  /** Source room id for ellipse walls. */
  ellipseSourceRoomId?: string;
  /** Wall belongs to a committed oriented bounding box of a room. */
  isObbWall?: boolean;
  /** Live-preview variant of oriented bounding box — excluded from room detection. */
  isObbPreview?: boolean;
  /** Source room id for OBB walls. */
  obbSourceRoomId?: string;
  /** Wall belongs to a committed regular n-gon enclosure of a room. */
  isNGonWall?: boolean;
  /** Live-preview variant of n-gon enclosure — excluded from room detection. */
  isNGonPreview?: boolean;
  /** Source room id for n-gon walls. */
  nGonSourceRoomId?: string;
  /** Wall belongs to a committed polygon-unroll visualization of a room. */
  isUnrollWall?: boolean;
  /** Live-preview variant of polygon unroll — excluded from room detection. */
  isUnrollPreview?: boolean;
  /** Source room id for unroll walls. */
  unrollSourceRoomId?: string;
  /** Wall belongs to a committed principal-axes overlay of a room. */
  isPrincipalAxisWall?: boolean;
  /** Live-preview variant of principal-axes overlay — excluded from room detection. */
  isPrincipalAxisPreview?: boolean;
  /** Source room id for principal-axis walls. */
  principalAxisSourceRoomId?: string;
  /** Wall belongs to a committed contour-line overlay of a room. */
  isContourWall?: boolean;
  /** Live-preview variant of contour-line overlay — excluded from room detection. */
  isContourPreview?: boolean;
  /** Source room id for contour walls. */
  contourSourceRoomId?: string;
  /** Wall belongs to a committed streamlines overlay of a room. */
  isStreamlineWall?: boolean;
  /** Live-preview variant of streamlines overlay — excluded from room detection. */
  isStreamlinePreview?: boolean;
  /** Source room id for streamline walls. */
  streamlineSourceRoomId?: string;
  /** Wall belongs to a committed noise-texture overlay of a room. */
  isNoiseTextureWall?: boolean;
  /** Live-preview variant of noise-texture overlay — excluded from room detection. */
  isNoiseTexturePreview?: boolean;
  /** Source room id for noise-texture walls. */
  noiseTextureSourceRoomId?: string;
  /** Wall belongs to a committed incircle overlay of a room. */
  isInCircleWall?: boolean;
  /** Live-preview variant of incircle overlay — excluded from room detection. */
  isInCirclePreview?: boolean;
  /** Source room id for incircle walls. */
  inCircleSourceRoomId?: string;
  /** Wall belongs to a committed tiling overlay of a room. */
  isTilingWall?: boolean;
  /** Live-preview variant of tiling overlay — excluded from room detection. */
  isTilingPreview?: boolean;
  /** Source room id for tiling walls. */
  tilingSourceRoomId?: string;
  /** Wall belongs to a committed squarified-treemap partition. */
  isTreemapWall?: boolean;
  /** Live-preview variant of squarified-treemap partition — excluded from room detection. */
  isTreemapPreview?: boolean;
  /** Source room id for treemap walls. */
  treemapSourceRoomId?: string;
  /** Whether this wall was generated by the Splitting Actions panel for a room. */
  isSplitWall?: boolean;
  /** Source room id for walls generated by Splitting Actions. */
  splitSourceRoomId?: string;
  /** Whether this wall was generated by the Inset Polygon panel for a room (live preview). */
  isInsetWall?: boolean;
  /** Source room id for walls generated by Inset Polygon. */
  insetSourceRoomId?: string;
  /** Door only: which end the hinge is on. "left" = start end, "right" = end end. */
  doorHinge?: "left" | "right";
  /** Door only: which side the door swings into. "left" = perpendicular left, "right" = perpendicular right. */
  doorPlacement?: "left" | "right";
  /** Door / Window: height from floor to top of opening, in meters. */
  lintelHeightM?: number;
  /** Window only: height from floor to bottom of opening, in meters. */
  sillHeightM?: number;
  /** Window only: when true, the 3D primitive renders the sash swung open; 2D is unaffected. */
  isOpen?: boolean;
  /** Plot boundary only: sub-type. */
  plotBoundaryType?: "road" | "plot" | "open" | "reservation" | "water" | "row";
  /** Plot boundary only: computed setback in meters. */
  setbackM?: number;
  /** Plot boundary + Road: road width in meters. */
  roadWidthM?: number;
  /** Plot boundary + Plot: whether it's a blank wall (no openings). */
  blankWall?: boolean;
  /** Plot boundary + Water: water body subtype. */
  waterSubtype?: "river" | "nala" | "lake" | "sea" | "canal";
  /** Plot boundary + Water: CRZ zone. */
  crzZone?: "I" | "II" | "III" | "IV";
  /** Plot boundary + ROW: ROW subtype. */
  rowSubtype?: "railway" | "metro" | "ht_line" | "pipeline" | "highway";

  // ── DCR / Regulation properties (plot boundary) ──
  /** Ground coverage percentage (e.g. 40) */
  groundCoveragePct?: number;
  /** Maximum building height in meters */
  maxHeightM?: number;
  /** Floor-to-floor height in meters */
  floorToFloorM?: number;
  /** Applicable regulation code (e.g. "DCR 33(7B)") */
  regulation?: string;
  /** Zone classification */
  zone?: string;

  // ── FSI properties (plot boundary) ──
  /** FSI multiplier for this segment */
  fsiMultiplier?: number;
  /** Deduction area in sq.m. (DP road / reservation segments) */
  deductionAreaSqm?: number;
  /** Whether this is surrendered land */
  isSurrenderedLand?: boolean;
  /** In-situ FSI available */
  inSituFsiAvailable?: number;

  // ── Entry / Access properties (plot boundary) ──
  /** Whether main entry is allowed from this side */
  allowsMainEntry?: boolean;
  /** Whether windows are allowed on this side */
  allowsWindows?: boolean;
  /** Whether NOC is required */
  nocRequired?: boolean;
  /** Whether this is the primary frontage */
  isPrimaryFrontage?: boolean;
  /** Proposed road widening in meters */
  proposedWideningM?: number;
}

/** Derived rectangle: four edges + spine. Computed from Wall via getWallPolygonGeometry in wallGeometry.ts. */
export interface WallPolygonGeometry {
  corners: Point[];
  edges: [Point, Point][];
  /** Center line along the wall (same as start → end). */
  spine: { start: Point; end: Point };
}

/** Room/area type classification. */
export type RoomType = "room" | "floorplate-boundary" | "plot-boundary";

export interface Room {
  id: string;
  points: Point[];
  fill: string;
  stroke: string;
  label?: string;
  netArea?: number;
  /** Area type: room (default), floorplate boundary, or plot boundary. */
  roomType?: RoomType;
  /** Region classification for rooms (only meaningful when roomType === "room"). */
  region?: "Core" | "Staircase" | "AHU" | "Electrical Room" | "Service" | "Lift" | "Toilet" | "Corridor";
  /** Zone-type sizing constraints used by the ZR pipeline. All optional, in metres² / dimensionless. */
  minArea?: number;
  maxArea?: number;
  maxRatio?: number;
  /** When true, render a clockwise/anticlockwise direction icon at the room's centroid. */
  showDirection?: boolean;
  // ── Site plan properties (plot-boundary rooms only) ──
  /** Ground coverage percentage */
  groundCoveragePct?: number;
  /** Maximum building height in meters */
  maxHeightM?: number;
  /** Floor-to-floor height in meters */
  floorToFloorM?: number;
  /** Maximum permissible FSI */
  maxFsi?: number;
  /** Applicable regulation code */
  regulation?: string;
  /** Max polygon optimization type */
  maxPolygonType?: "normal" | "axis-aligned" | "edge-sitting";
  /** Zone classification */
  zone?: string;
}

export type ObjectKind = "rect" | "circle" | "polygon" | "freehand" | "text" | "segment";

export interface BaseObject {
  id: string;
  x: number;
  y: number;
  rotation: number;
  stroke: string;
  fill: string;
}

export interface RectObject extends BaseObject {
  kind: "rect";
  width: number;
  height: number;
}

export interface CircleObject extends BaseObject {
  kind: "circle";
  radius: number;
}

export interface PolygonObject extends BaseObject {
  kind: "polygon";
  points: number[];
}

export interface FreehandObject extends BaseObject {
  kind: "freehand";
  points: number[];
}

export interface TextObject extends BaseObject {
  kind: "text";
  text: string;
  fontSize: number;
}

export type SegmentSubtype = "drawn" | "adjacency";
export type AdjacencyConstraint = "connection" | "repulsion";

export interface SegmentObject extends BaseObject {
  kind: "segment";
  points: number[];
  measurements: string[];
  totalText: string;
  /** "drawn" (default, manually drawn) or "adjacency" (auto-computed between two rooms). */
  segmentSubtype?: SegmentSubtype;
  /** For adjacency subtype: endpoints reference room IDs and points are derived from centroids. */
  aRoomId?: string;
  bRoomId?: string;
  /** For adjacency subtype: the relation type. */
  constraint?: AdjacencyConstraint;
}

export type FloorObject = RectObject | CircleObject | PolygonObject | FreehandObject | TextObject | SegmentObject;

export interface FurnitureItem {
  id: string;
  type: "bed" | "sofa" | "table" | "chair" | "door" | "window";
  x: number;
  y: number;
  rotation: number;
  scaleX: number;
  scaleY: number;
  /** Door only: swing arc sweep in degrees (0 = closed, 90 = fully open). Default 90 when omitted. */
  doorSwingDeg?: number;
  /** Door only: when true, swing arc opens on the opposite face of the wall (inside vs outside in plan). */
  doorSwingFlip?: boolean;
  /** Door only: the two room labels this door connects. Used to reposition when rooms move. */
  connectionRooms?: [string, string];
}

export interface ImageUnderlay {
  src: string;
  x: number;
  y: number;
  width: number;
  height: number;
  opacity: number;
  scale: number;
  locked: boolean;
}

export interface RoomConstraint {
  label: string;
  minArea: number;
  maxRatio: number;
}

export interface FloorPlanModel {
  walls: Wall[];
  rooms: Room[];
  objects: FloorObject[];
  furniture: FurnitureItem[];
  imageUnderlay: ImageUnderlay | null;
  constraints?: {
    rooms: RoomConstraint[];
    connections: [string, string][];
  };
}

/** Stored state from an auto-generated floor plan, enabling interactive room dragging. */
export interface GeneratedLayoutState {
  /** The generation config used (boundary, rooms, connections, etc.) */
  config: import("./floorplanAlgorithms").GenerateConfig;
  /** Current seed positions in meters (used to re-run BSP on drag) */
  seedPositions: Record<string, { x: number; y: number }>;
  /** Current room rectangles in pixel coords (for hit-testing drag targets) */
  roomRects: Array<{ label: string; x: number; y: number; w: number; h: number }>;
}
